services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./vhosts:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
      # - ../api.demopizza.ru/storage:/var/www/api.demopizza.ru/storage:ro
    command: |
      /bin/sh -c "
      while true; do
        sleep 24h & wait \$!;
        nginx -s reload;
      done &
      nginx -g 'daemon off;'
      "
    networks:
      - docker-network

  certbot-service:
    image: certbot/certbot:latest
    container_name: certbot-container
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/var:/var/lib/letsencrypt
    entrypoint: |
      /bin/sh -c "
      trap 'exit 0' TERM;
      while true; do
        certbot renew;
        sleep 24h & wait \$!;
      done
      "
    networks:
      - docker-network

networks:
  docker-network:
    name: docker-network
    driver: bridge
