server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _; # Ловит абсолютно все домены, направленные на этот VPS

    # Общая локация для проверки доменов роботом Let's Encrypt
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Всех остальных обычных пользователей с любого домена 
    # автоматически и безопасно перенаправляем на HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}