server {
   listen 443 ssl;
   server_name admin.kgb-orenburg.ru; 

   ssl_certificate /etc/letsencrypt/live/admin.kgb-orenburg.ru/fullchain.pem;
   ssl_certificate_key /etc/letsencrypt/live/admin.kgb-orenburg.ru/privkey.pem;

   location = /manifest.webmanifest {
      root /var/projects/admin.kgb-orenburg.ru/dist;
      try_files $uri =404;
      types {
          application/manifest+json webmanifest; #чтобы отображался как json в devtools
      }
   }

   location / {
      root /var/projects/admin.kgb-orenburg.ru/dist;
      try_files $uri $uri/ /index.html;
   }
}