server {
   listen 443 ssl;
   server_name demopizza.ru; 

   ssl_certificate /etc/letsencrypt/live/demopizza.ru/fullchain.pem;
   ssl_certificate_key /etc/letsencrypt/live/demopizza.ru/privkey.pem;

   location = /manifest.json {
      proxy_pass http://demopizza-api-container:5000/api/v1/pwa/manifest.json;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
   }

   location / {
      root /var/projects/demopizza.ru/dist;
      try_files $uri $uri/ /index.html;
   }
}