server {
   listen 443 ssl;
   server_name food-it.ru; 

   ssl_certificate /etc/letsencrypt/live/food-it.ru/fullchain.pem;
   ssl_certificate_key /etc/letsencrypt/live/food-it.ru/privkey.pem;

   location / {
      root /var/projects/food-it.ru/dist;
      try_files $uri $uri/ /index.html;
   }
}